framework:
    rate_limiter:
        forgot_password_email:
            policy: sliding_window
            limit: 1
            interval: 5 minutes
            lock_factory: null # todo remove in Symfony 7.3
