framework:
    rate_limiter:
        user_registration:
            policy: sliding_window
            limit: 1
            interval: 30 minutes
        verify_email:
            policy: sliding_window
            limit: 1
            interval: 5 minutes
        forgot_password_email:
            policy: sliding_window
            limit: 1
            interval: 5 minutes
