framework:
    router:
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        default_uri: '%env(APP_URL)%'

when@dev:
    parameters:
        env(SYMFONY_PROJECT_DEFAULT_ROUTE_URL): '%env(APP_URL)%'

    framework:
        router:
            default_uri: '%env(SYMFONY_PROJECT_DEFAULT_ROUTE_URL)%'

when@prod:
    framework:
        router:
            strict_requirements: null
