workers:
    tailwind:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch']

    messenger:
        cmd: ['symfony', 'console', 'messenger:consume', 'async']
        watch: ['config', 'src', 'templates']
